const Project = require('../models/Project');
const ScopeItem = require('../models/ScopeItem');
const ClientRequest = require('../models/ClientRequest');
const ChangeOrder = require('../models/ChangeOrder');
const Notification = require('../models/Notification');

/** Structured app error helper */
const appError = (status, appCode, message) => {
  const err = new Error(message);
  err.status = status;
  err.appCode = appCode;
  return err;
};

// ─── GET /api/projects ───────────────────────────────────────────────────────
// List all projects belonging to the authenticated freelancer
const getProjects = async (req, res, next) => {
  try {
    const projects = await Project.find({ freelancerId: req.user.id })
      .sort({ createdAt: -1 })
      .select('title clientName status totalPrice totalHours portalToken createdAt');

    return res.status(200).json({ projects });
  } catch (err) {
    next(err);
  }
};

// ─── POST /api/projects ──────────────────────────────────────────────────────
// Create a new project; portalToken auto-generated by the pre-save hook
const createProject = async (req, res, next) => {
  try {
    const { title, clientName, hourlyRate } = req.body;

    // Explicit validation (Mongoose schema also validates, belt-and-suspenders)
    if (!title || !clientName || hourlyRate === undefined) {
      return next(
        appError(400, 'VALIDATION_ERROR', 'title, clientName, and hourlyRate are required')
      );
    }

    const rate = Number(hourlyRate);
    if (isNaN(rate) || rate <= 0 || rate > 100000) {
      return next(
        appError(400, 'VALIDATION_ERROR', 'hourlyRate must be a number greater than 0 and at most 100000')
      );
    }

    const project = await Project.create({
      freelancerId: req.user.id,
      title: title.trim(),
      clientName: clientName.trim(),
      hourlyRate: rate,
    });

    return res.status(201).json({ project });
  } catch (err) {
    next(err);
  }
};

// ─── GET /api/projects/:id ───────────────────────────────────────────────────
const getProject = async (req, res, next) => {
  try {
    const project = await Project.findById(req.params.id);

    if (!project) {
      return next(appError(404, 'NOT_FOUND', 'Project not found'));
    }

    // Ownership check (NFR3 / Section 19)
    if (project.freelancerId.toString() !== req.user.id) {
      return next(appError(403, 'FORBIDDEN', 'You do not have access to this project'));
    }

    return res.status(200).json({ project });
  } catch (err) {
    next(err);
  }
};

// ─── PUT /api/projects/:id ───────────────────────────────────────────────────
const updateProject = async (req, res, next) => {
  try {
    const project = await Project.findById(req.params.id);

    if (!project) {
      return next(appError(404, 'NOT_FOUND', 'Project not found'));
    }

    if (project.freelancerId.toString() !== req.user.id) {
      return next(appError(403, 'FORBIDDEN', 'You do not have access to this project'));
    }

    const { title, clientName, hourlyRate } = req.body;

    // Only update provided fields
    if (title !== undefined) {
      if (title.trim().length < 3 || title.trim().length > 100) {
        return next(appError(400, 'VALIDATION_ERROR', 'title must be 3–100 characters'));
      }
      project.title = title.trim();
    }

    if (clientName !== undefined) {
      if (clientName.trim().length < 2 || clientName.trim().length > 100) {
        return next(appError(400, 'VALIDATION_ERROR', 'clientName must be 2–100 characters'));
      }
      project.clientName = clientName.trim();
    }

    if (hourlyRate !== undefined) {
      const rate = Number(hourlyRate);
      if (isNaN(rate) || rate <= 0 || rate > 100000) {
        return next(appError(400, 'VALIDATION_ERROR', 'hourlyRate must be greater than 0 and at most 100000'));
      }
      project.hourlyRate = rate;
    }

    await project.save();

    return res.status(200).json({ project });
  } catch (err) {
    next(err);
  }
};

// ─── DELETE /api/projects/:id ────────────────────────────────────────────────
// Cascades: deletes all scope items, requests, change orders, and notifications
const deleteProject = async (req, res, next) => {
  try {
    const project = await Project.findById(req.params.id);

    if (!project) {
      return next(appError(404, 'NOT_FOUND', 'Project not found'));
    }

    if (project.freelancerId.toString() !== req.user.id) {
      return next(appError(403, 'FORBIDDEN', 'You do not have access to this project'));
    }

    // Cascade deletes
    await ScopeItem.deleteMany({ projectId: project._id });
    await ChangeOrder.deleteMany({ projectId: project._id });
    await ClientRequest.deleteMany({ projectId: project._id });
    await Notification.deleteMany({ projectId: project._id });
    await project.deleteOne();

    return res.status(200).json({ message: 'Project deleted successfully' });
  } catch (err) {
    next(err);
  }
};

module.exports = { getProjects, createProject, getProject, updateProject, deleteProject };
